language: python
python:
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
  - "nightly"
install:
  - pip install -r requirements.txt
  #- pip install -U pytest
  # update npm
  - npm install npm -g
  - npm install -g snyk
  - snyk test
#script:
#  #- pytest
after_success:
  - snyk monitor