language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  #- pip install -U pytest
  # update npm
  - npm install npm -g
  - npm install -g snyk
  - snyk test
script:
  - echo 0
  #- pytest
after_success:
  - snyk monitor